language: ruby
install: bundle install
sudo: false
script:
 - bundle exec rake
rvm:
  - 2.2
  - 2.1
  - 2.0
  - 1.9.3
gemfile:
  - gemfiles/3.0.gemfile
  - gemfiles/3.1.gemfile
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile
