language: ruby
install: bundle install
script:
 - bundle exec rake
rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
gemfile:
  - gemfiles/3.0.gemfile
  - gemfiles/3.1.gemfile
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
matrix:
  exclude:
    - rvm: 1.9.2
      gemfile: gemfiles/4.0.gemfile
